### ISSUE TITLE
Jekyll

### ISSUE THREAD

**Issue by sburns** [redcap-tools/redcap-tools.github.io#1]
In the interest of getting up a page quickly, I used the automatic site generator but this should be a jekyll site.

**Comment by wibeasley** [comment]
I'm comfortable setting up a [Jekyl / R Markdown hybrid](http://rmarkdown.rstudio.com/) page for this org ([example-1](http://ouhscbbmc.github.io/MReportingPublic/) and [example-2](http://liveoak.github.io/NlsyLinks/) -notice any similarities?).  But it's pretty biased towards the experience and tools of R users, so not within the spirit of this org. 

If someone sets up a structure that's more agnostic, I'm happy to contribute.  Especially to the list of related tools.  I like the [rOpenSci example](https://ropensci.org/packages/) that @haozhu233 mentioned in #2.
