### ISSUE TITLE
Need travis.yml file

### ISSUE THREAD

**Issue by wibeasley** [redcap-tools/redcap-tools.github.io#15]
I saw that Travis was added to the repo, but it looks like the yml file still needs to be added.  I get the reason behind Travis checks [for R packages](https://travis-ci.org/OuhscBbmc/REDCapR/builds), but I haven't researched what gets checked for a Jekyll site.  @sburns, I assume this is something you're comfortable with?

https://travis-ci.org/redcap-tools/redcap-tools.github.io/builds
![image](https://cloud.githubusercontent.com/assets/1372890/11112456/ea0db046-88d8-11e5-96e6-30386b2fed4e.png)

(I'm guessing Travis's notification system is the reason @sburns knew to [slap my hand](https://github.com/redcap-tools/redcap-tools.github.io/commit/121653fb614fabb35c2506605603ef5849b23dca#commitcomment-14346802) so soon after my offense.)

**Comment by sburns** [comment]
> I'm guessing Travis's notification system is the reason @sburns knew to slap my hand so soon after my offense.

**Comment by sburns** [comment]
> I'm guessing Travis's notification system is the reason @sburns knew to slap my hand so soon after my offense.

I'm just giving you a hard time. I looked into [setting up a travis ci build](http://jekyllrb.com/docs/continuous-integration/) for PRs against the site but didn't follow through yet.

**Comment by sburns** [comment]
Closed with #16

**Comment by wibeasley** [comment]
[_ah hem_](https://github.com/redcap-tools/redcap-tools.github.io/commit/6ed8a286c973f61b11e19c6c7b551e5f0bb866a9)  (Still Joking.)

Yeah, I appreciated the teasing, while also being a nudge in the right direction.

**Comment by sburns** [comment]
LOL
