### ISSUE TITLE
redcap-test-datasets

### ISSUE THREAD

**Issue by wibeasley** [redcap-tools/redcap-tools.github.io#17]
An open question to everyone: would this org be a good home for the [redcap-test-datasets](https://github.com/OuhscBbmc/redcap-test-datasets) project?

@aarenson and I talked about this a while ago.  It's goal is to cover different scenarios that REDCap API libraries should test.  There's some scaling efficiency if each library doesn't have to think up its own scenario, and expected returned csv.

Regardless where it lives, I'm going to add it to the [projects](http://redcap-tools.github.io/projects/) page, in the "Code Samples and Snippets" table.  I think it could belong to "Common Resources" instead, but since I'm 50/50, I'll put it int he table that has only one row.

If anyone has thoughts or objection, I'm happy to move or remove it.

**Comment by aarenson** [comment]
Seems like a good place for test datasets.

**Comment by aarenson** [comment]
```
Looks good to me.
```

Andy

On Mon, Nov 23, 2015 at 09:06:54PM -0800, Will Beasley wrote:

> An open question to everyone: would this org be a good home for the [redcap-test-datasets](https://github.com/OuhscBbmc/redcap-test-datasets) project?
> 
> @aarenson and I talked about this a while ago.  It's goal is to cover different scenarios that REDCap API libraries should test.  There's some scaling efficiency if each library doesn't have to think up its own scenario, and expected returned csv.
> 
> Regardless where it lives, I'm going to add it to the [projects](http://redcap-tools.github.io/projects/) page, in the "Code Samples and Snippets" table.  I think it could belong to "Common Resources" instead, but since I'm 50/50, I'll put it int he table that has only one row.
> 
> If anyone has thoughts or objection, I'm happy to move or remove it.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/redcap-tools/redcap-tools.github.io/issues/17

## 

Andrew D. Arenson                                      | aarenson (@) iu.edu
Advanced Biomedical IT Core, Research Technologies, UITS  | W (317) 278-1208
RT is a PTI Cyberinfrastructure & Service Center          | C (317) 679-4669
Indiana University Purdue University Indianapolis         | F (317) 278-1852

**Comment by wibeasley** [comment]
done: https://github.com/redcap-tools/redcap-test-datasets
