### ISSUE TITLE
What should move?  What should stay?

### ISSUE THREAD

**Issue by wibeasley** [redcap-tools/redcap-tools.github.io#2]
I like the concept of this organization and the [organization's website](http://redcap-tools.github.io/) that @sburns just started.  I believe that any active and semi-active projects should be _listed_ on the page (regardless if they're on GitHub).  I like that that anyone can go to this page  --especially those not officially in the consortium.  However I'm not convinced that every project should be _hosted_ by the GitHub organization.  I'm starting this post to see what other people think.

There are some scenarios that make a lot of sense to me to move, including the reasons mentioned in https://github.com/sburns/PyCap/issues/58.  Chris Nefcy has offered some C# code that's likely a fit here too.

However, I'm wondering if the move is unnecessarily disruptive in other scenarios.  If a repo has sustained momentum in it's current org, I'm tentative moving it.  I'm particularly hesitant to disrupt [REDCapR](https://github.com/OuhscBbmc/REDCapR) status; I'm concerned that moving it will make it less clear which people are responsible for improvements, maintenance, & user-support.

Admittedly I don't have much experience to draw from.  Has anyone been involved with a reorganization/transition before at this medium-sized scale?  Under what conditions is it beneficial and encourage broader participation?  Under what conditions does it make things murkier and weaken accountability?  (Feel free to propose reasons why I'm being unnecessarily possessive and short-sighted.)

(cc others who've contributed to REDCap-related repos: @haozhu233 @rparrish @nutterb @123andy @aarenson @pbchase  @sburns.  Please include anyone else whom I haven't met that might be interested in this conversation.)

**Comment by haozhu233** [comment]
I don't have a definitive opinion in my mind either but I do feel in the same way as @wibeasley does. 

Also, I just checked how [rOpenSci](https://ropensci.org) handles their repos and I found that on the one hand, they do have most of their packages unified into one account but they still have a package called `dataone` hosted in its original organization. 

My understanding is that if we can build a good index page as good as [this](https://ropensci.org/packages/), people won't mind too much if one or two packages are not "technically" stored under the name of the organization.

**Comment by aarenson** [comment]
Sounds right -- put things here if it's not disruptive, otherwise at least have a single place here to learn about related projects.

I want to be careful if I move PHPCap to this org that I'm not giving up my current level of control. I'm happy to negotiate joint control for people who show interest in collaborating.

I don't know what it takes to move a repository from one org to another.

**Comment by 123andy** [comment]
FYI - we're in the process of evaluating a better consortium communication platform which could assist in the multiple repository problem...

-A

On Oct 7, 2015, at 6:27 PM, aarenson <notifications@github.com<mailto:notifications@github.com>> wrote:

Sounds right -- put things here if it's not disruptive, otherwise at least have a single place here to learn about related projects.

I want to be careful if I move PHPCap to this org that I'm not giving up my current level of control. I'm happy to negotiate joint control for people who show interest in collaborating.

I don't know what it takes to move a repository from one org to another.

**Comment by sburns** [comment]
I don't want there to be pressure or coercion on any part to move projects here. My goal with this organization is:
- A space for projects whose initial developer(s) have moved on or can't dedicate enough resources to properly steward the project a place to live.
- Connect developers to projects they may want to contribute time and effort to either improve the quality or help maintain existing functionality into the future.
- Connect developers to one another. We're all developing cool tools in parallel, siloed off in our institutions. (Another repo I'd like to see in this organization is called _Ideas_).
- Publicity. Personally speaking, I wasn't out to make $ when writing PyCap or any of the repos I wrote while at Vanderbilt, but I sure did promote both them and my name where I could. We're being disingenuous to say we're writing this software and then talking about it in blogs and at conferences for purely community reasons.

I think every project in this organization should prominently display in their README loud and center the current maintainers for accountability in handling issues. (A page on this site as to what should be done before moving a repo would be helpful).

I'm really not interested in using this organization to exert control over projects. Every software project of any significance has some amount of politics behind it (who built it, who paid for that time, what the university or group thinks they "deserve") and this organization doesn't need to contribute to that.

> FYI - we're in the process of evaluating a better consortium communication platform which could assist in the multiple repository problem...

I'd be interested to see what this looks like. GitHub seems to serve well very-large software projects (django, rails, bootstrap, etc).

> I don't know what it takes to move a repository from one org to another.

It's relatively simple, in the settings page for the repo there's a place to change the owner (in the github sense, not the intellectual rights). GitHub is also good about forwarding old URLs to the correct repo (e.g. if someone uses an old clone URL, it will just work).

> My understanding is that if we can build a good index page as good as this, people won't mind too much if one or two packages are not "technically" stored under the name of the organization.

This site _definitely_ needs a Projects page and I hope I've made it clear that we shouldn't discriminate based on where that project is housed. That the repo is under the original developer or this organization is an implementation detail.

**Comment by pbchase** [comment]
I don't think anyone should feel compelled to move their projects here if those projects have a good home. I am concerned about homeless projects.  I also think this could be a good home for projects that have a home but are not getting attention for want of interest or funds from those who are hosting them.

Few of my REDCap projects are _mine_. They are my employer's. I work on them but I also have peers at UF who will continue to work on them even if I get hit but a bus tomorrow. As our org is paying our salaries we will continue to promote our org by hosting our repos within our Github organization. 

Philip

**Comment by sburns** [comment]
Great points @pbchase. "Abandoned" is a strong word but it applies here too. This can be a place to bring abandoned projects back from the dead.

**Comment by wibeasley** [comment]
Great, it sounds like everyone's approach and expectations are compatible (FWIW, I never thought anyone was feeling coerced.)  I'm closing the issue now, but I'd love to hear any additional beliefs (or rules of thumb) about which types of repos fit best within which org.

---

@sburns & @pbchase, I hadn't thought much about a university's role in all this.  Thanks for bringing that up.

@123andy, are you saying the new platform might potentially host the repos?  Or just be more open (and Googleable) than the consortium's current hidden site?  

For the role that @sburns and other have described for this org, it's hard for me to imagine a better platform.  Especially how easily it is to move a repo between orgs (and the old links forward automatically).  You probably won't be surprised that I've thought that the REDCap team should create their own official GitHub org.
