### ISSUE TITLE
Release badge for the new ruby redcap repo

### ISSUE THREAD

**Issue by wibeasley** [redcap-tools/redcap-tools.github.io#25]
As pointed out by @peterclark in https://github.com/redcap-tools/redcap-tools.github.io/commit/77d2123147dc2d6a3e63cdfe70a6cc50c03658f1#commitcomment-21001617, the release badge for his new [redcap](https://github.com/peterclark/redcap/releases) package in Ruby isn't correctly picking up his release.  It's been only a few hours since that was released.  I'll give it some more time.  Maybe that shields.io server caches results for a long time.

@peterclark, if you figure out how to fix it, please feel free to submit a PR.

https://img.shields.io/github/release/peterclark/redcap.svg

**Comment by wibeasley** [comment]
@peterclark, I looked at this again and still don't have a solution.  Any change the repo organization and/or name was changed *after* the last release date?

**Comment by wibeasley** [comment]
@peterclark, I tried again and still don't understand why it's working.  I'm removing that badge (along with the others -but I think all of those didn't have releases).

if you figure out how to fix it, please feel free to submit a PR.  It seems to follow the [pattern](https://shields.io/#/examples/version): `https://img.shields.io/github/release/:user/:repo.svg`


https://img.shields.io/github/release/peterclark/redcap.svg

**Comment by peterclark** [comment]
@wibeasley - yeah I'm not sure what the issue is either. Thanks for looking into it.
