### ISSUE TITLE
multiple permissions

### ISSUE THREAD

**Issue by reductionist** [redcap-tools/redcap-tools.github.io#32]
Hi all, very sorry for posting this here, but I'm having a hard time finding a RedCAP forum accessible to end users.  My question is whether it's possible to grant and change permissions for a single person on multiple projects.  I have a couple hundred projects, and need to grant one person access to all of them.  Is there an easy way to do this, and if not, could it be scripted?

Thanks!

**Comment by wibeasley** [comment]
Hi @reductionist, user management is not my area of REDCap.  But from what I understand, there's no way to do this unless you develop/install a REDCap plugin.

Sorry you're having a hard time finding a suitable location to post this.  
Are you the REDCap administrator for your institution?  If so, you should have access to https://community.projectredcap.org.  If not, your admin can post this question there for you.  

This page has more info about the process: https://projectredcap.org/resources/community/
