### ISSUE TITLE
Include link to External Modules

### ISSUE THREAD

**Issue by wibeasley** [redcap-tools/redcap-tools.github.io#40]
@pbchase, @aarenson, @haozhu233, @rparrish, or anyone else interested:

With the recent introduction of External Modules, does it make sense to include a link to the [available list](https://redcap.vanderbilt.edu/consortium/modules/index.php)?  Is the best place in the 'Common Resources' section of http://redcap-tools.github.io/projects/?

Paraphrasing their page, the REDCap Tools description would be roughly 
>External Modules are add-on packages that extend functionality, either at the system level or project level. The REDCap Repo is a centralized repository of curated External Modules that can be installed by a REDCap administrator.

**Comment by aarenson** [comment]
Yes, including it makes sense to me. Not sure about the best place to include it. Common Resources is reasonable. Could also be a standalone section.

**Comment by pbchase** [comment]
I think adding the EMs to the list is a good idea. Pointing at the REDCap Repo is also wise. I think it would also be good to include some text like this

> Many of the public module repositories on GitHub have been tagged with the topic `redcap-external-module`. They can be accessed at [https://github.com/topics/redcap-external-module](https://github.com/topics/redcap-external-module) Many of these External Modules are published in the REDCap Repo, but the search many more who others have not elected to place in the REDCap Repo at this time. They can provide valuable resources for module development and might be useful in and of themselves.
