### ISSUE TITLE
Getting surveys links through API REDCap

### ISSUE THREAD

**Issue by zic10** [redcap-tools/redcap-tools.github.io#48]
I am using REDCap for a project, and I need to obtain the participant surveys links through the REDCap API to manage reminders externally to REDCap.
In the API Playground of the REDCap, when I run the "Export a Survey Link" method to get the survey link from a user who has not yet responded, I get an error: {"error": "An unknown error occurred"}
However, if the user has already responded to the survey, the API method works and returns the link.
The REDCap version is 6.14.0

Any suggestions? Is there any way to get the surveys links from participant whether or not they responded?
Thank you

**Comment by wibeasley** [comment]
@zic10, that REDCap version is 3.5 years old.  Maybe newer versions handle this better?  There are lots of reasons to keep the installation fresher.

The online [changelog](https://community.projectredcap.org/articles/13/changelog-standard-release.html) goes back to only 8.10.0, but I see some work done on survey links.  I see some discussions about it on the [forms](https://community.projectredcap.org/search.html?f=&type=question+OR+idea+OR+kbentry&redirect=search%2Fsearch&sort=relevance&q=survey+links+api) too.  Hopefully this has been addressed in the code.

If you're still having problems after an upgrade and you don't get a good response here, maybe your site's REDCap admin could post the question to the [API space in the private forums](https://community.projectredcap.org/spaces/20/index.html)?

**Comment by zic10** [comment]
Thanks a lot @wibeasley 
I will follow your suggestions
