### ISSUE TITLE
Add REDCapTidieR

### ISSUE THREAD

**Issue by wibeasley** [redcap-tools/redcap-tools.github.io#55]
Add an entry for the great new package: https://github.com/CHOP-CGTDataOps/REDCapTidieR

cc: @rsh52, @skadauke, @ezraporter

**Comment by wibeasley** [comment]
Anything you'd like to change before I close the issue?

https://redcap-tools.github.io/projects/

![image](https://user-images.githubusercontent.com/1372890/193306780-5106793a-23fb-4ab0-a96b-61b02e1156f8.png)

**Comment by rsh52** [comment]
Nothing from my end, but would like to get @skadauke's thoughts before finalizing. I like the hyperlink to the `tidy` vignette. 

Thank you for putting us on this! It looks great, a fantastic resource.

**Comment by wibeasley** [comment]
@skadauke, just change your entry if there's something else you'd like: https://github.com/redcap-tools/redcap-tools.github.io/blob/main/_data/libraries.yml
