### ISSUE TITLE
icon for `redcap-tools` org?

### ISSUE THREAD

**Issue by wibeasley** [redcap-tools/redcap-tools.github.io#7]
I spent a few minutes on https://freeiconmaker.com and http://www.flaticon.com/free-icon/baseball-cap_72588#term=cap&page=1&position=36 as an experiment for replacing the default icon for this org.  Any thoughts?  If anyone likes it for this org, I'll pay the $10 so we don't have to figure out how to include the correct attributes everywhere.  (You don't have to include a credit if you pay $10.)

![freeiconmaker_2](https://cloud.githubusercontent.com/assets/1372890/11018930/16560fc6-85a6-11e5-87a6-172c42d65f7f.png) ![freeiconmaker_0](https://cloud.githubusercontent.com/assets/1372890/11018934/2b25617c-85a6-11e5-9e31-fd67daa46ca0.png)

**Comment by haozhu233** [comment]
It looks great to me! I'm thinking after you make a decision on the icon. We can convert it to a Font-awesome style icon through either https://icomoon.io or http://fontcustom.github.io/fontcustom/ so we can easily use the logo in webpages.

**Comment by sburns** [comment]
:+1:

**Comment by wibeasley** [comment]
I've added the logos to the repo at https://github.com/redcap-tools/redcap-tools.github.io/tree/master/images/logos.  What's the best practice to follow for their name & location?  Should it go in `includes/`?  I'm willing to follow anyone else's convention/preference.

@haozhu233, I don't know much about webdesign, and I don't really know what I'm talking about fonts.  I didn't see a way to download an svg from FreeIconMaker.  The only option was png.  Should we look for another icon source (that provides svgs)?  Or should we use this one (and I'll pay them $10)?

![image](https://cloud.githubusercontent.com/assets/1372890/11043640/62a3a1e8-86e3-11e5-9805-363fc3ccd50c.png)

**Comment by sburns** [comment]
> What's the best practice to follow for their name & location?

I think /assets or /static would be better.

**Comment by wibeasley** [comment]
@sburns done: https://github.com/wibeasley/redcap-tools.github.io/commit/decd84719a357e1a072fca0cbf30729171c19766.  And I'm to follow your lead on anything else too.

**Comment by sburns** [comment]
I'd say this can be closed, no?

**Comment by wibeasley** [comment]
@sburns, I was waiting to hear @haozhu233 's opinion about if we should find a different icon tool that would allow us to convert it into a FA-like character.

If you guys don't think it's too important, I'll happily pay the $10 and close the issue.

**Comment by haozhu233** [comment]
Ach, sorry, @wibeasley, I should have given you an update on that. I was planning to check out some png to svg tools later tonight and see if it works. I think that shouldn't be a problem. :D

Also, should we also have the original image of the cap (black cap with transparent background)? I can also pack them into the custom FA-style css file.

**Comment by wibeasley** [comment]
Cool, @haozhu233.  And I'm not married to that icon tool or the design.  If there's a more streamlined approach to get the type of logo/icon you want, feel free to do it yourself, or point me to it.  If there's an better/easier path to get the product you want, I'm not advocating that you spend 30 minutes converting my half-assed 2-minute png to an svg.

And if you want just a flat silhouette of the cap (without any gradient) as an svg, I got it [here](http://www.flaticon.com/free-icon/baseball-cap_72588#term=cap&page=1&position=36).

**Comment by haozhu233** [comment]
https://github.com/redcap-tools/redcap-tools.github.io/pull/12
I just created a pull request on that. 
I also took this opportunity to learn a little bit more about svg as I feel like we may need to play with this format a lot in R in the future. :)

**Comment by wibeasley** [comment]
Closed with 937bb1f981db99bc291045e4a2f2093eb6a85307
