### ISSUE TITLE
Fix table of projects

### ISSUE THREAD

**Issue by wibeasley** [redcap-tools/redcap-tools.github.io#8]
The table i just added is bad, 
- [x] it needs some CSS to make it legible
- [x] I need to figure out why the badges aren't linking correctly on github.io.

![image](https://cloud.githubusercontent.com/assets/1372890/11043606/306e3120-86e3-11e5-9a42-57fba4e559de.png)

**Comment by haozhu233** [comment]
https://github.com/badges/shields/issues/480
https://github.com/badges/shields/issues/445

Does it help?

**Comment by wibeasley** [comment]
@haozhu233 That second link is perfect.  It sounds like that it won't be a problem on our github.io site now that it's cached.  I pulled the screenshot above just a minute or two after merging the pull request.  It's working now.

![image](https://cloud.githubusercontent.com/assets/1372890/11044162/cf96966e-86e5-11e5-884c-7c78234fefbb.png)
